package com.wg.waimao.dao;

import com.wg.waimao.entity.UserMessage;
import java.util.List;

public interface UserMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_message
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_message
     *
     * @mbggenerated
     */
    int insert(UserMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_message
     *
     * @mbggenerated
     */
    UserMessage selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_message
     *
     * @mbggenerated
     */
    List<UserMessage> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserMessage record);
}