package com.wg.waimao.entity;

import java.io.Serializable;
import java.util.Date;

public class Article implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_comment
     *
     * @mbggenerated
     */
    private String articleComment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.release_date
     *
     * @mbggenerated
     */
    private Date releaseDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.pv
     *
     * @mbggenerated
     */
    private Long pv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.image
     *
     * @mbggenerated
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table article
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.id
     *
     * @return the value of article.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.id
     *
     * @param id the value for article.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.title
     *
     * @return the value of article.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.title
     *
     * @param title the value for article.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_comment
     *
     * @return the value of article.article_comment
     *
     * @mbggenerated
     */
    public String getArticleComment() {
        return articleComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_comment
     *
     * @param articleComment the value for article.article_comment
     *
     * @mbggenerated
     */
    public void setArticleComment(String articleComment) {
        this.articleComment = articleComment == null ? null : articleComment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.release_date
     *
     * @return the value of article.release_date
     *
     * @mbggenerated
     */
    public Date getReleaseDate() {
        return releaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.release_date
     *
     * @param releaseDate the value for article.release_date
     *
     * @mbggenerated
     */
    public void setReleaseDate(Date releaseDate) {
        this.releaseDate = releaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.pv
     *
     * @return the value of article.pv
     *
     * @mbggenerated
     */
    public Long getPv() {
        return pv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.pv
     *
     * @param pv the value for article.pv
     *
     * @mbggenerated
     */
    public void setPv(Long pv) {
        this.pv = pv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.image
     *
     * @return the value of article.image
     *
     * @mbggenerated
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.image
     *
     * @param image the value for article.image
     *
     * @mbggenerated
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", title=").append(title);
        sb.append(", articleComment=").append(articleComment);
        sb.append(", releaseDate=").append(releaseDate);
        sb.append(", pv=").append(pv);
        sb.append(", image=").append(image);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}