package com.wg.waimao.entity;

import java.io.Serializable;
import java.math.BigDecimal;

public class Product implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.cname
     *
     * @mbggenerated
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.ename
     *
     * @mbggenerated
     */
    private String ename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.price
     *
     * @mbggenerated
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.star_level
     *
     * @mbggenerated
     */
    private Integer starLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_desc
     *
     * @mbggenerated
     */
    private String productDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.extra_info
     *
     * @mbggenerated
     */
    private String extraInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.summary
     *
     * @mbggenerated
     */
    private String summary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.help
     *
     * @mbggenerated
     */
    private String help;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.img1
     *
     * @mbggenerated
     */
    private String img1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.img2
     *
     * @mbggenerated
     */
    private String img2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.img3
     *
     * @mbggenerated
     */
    private String img3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.id
     *
     * @return the value of product.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.id
     *
     * @param id the value for product.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.cname
     *
     * @return the value of product.cname
     *
     * @mbggenerated
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.cname
     *
     * @param cname the value for product.cname
     *
     * @mbggenerated
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.ename
     *
     * @return the value of product.ename
     *
     * @mbggenerated
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.ename
     *
     * @param ename the value for product.ename
     *
     * @mbggenerated
     */
    public void setEname(String ename) {
        this.ename = ename == null ? null : ename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.type
     *
     * @return the value of product.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.type
     *
     * @param type the value for product.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.price
     *
     * @return the value of product.price
     *
     * @mbggenerated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.price
     *
     * @param price the value for product.price
     *
     * @mbggenerated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.star_level
     *
     * @return the value of product.star_level
     *
     * @mbggenerated
     */
    public Integer getStarLevel() {
        return starLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.star_level
     *
     * @param starLevel the value for product.star_level
     *
     * @mbggenerated
     */
    public void setStarLevel(Integer starLevel) {
        this.starLevel = starLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_desc
     *
     * @return the value of product.product_desc
     *
     * @mbggenerated
     */
    public String getProductDesc() {
        return productDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_desc
     *
     * @param productDesc the value for product.product_desc
     *
     * @mbggenerated
     */
    public void setProductDesc(String productDesc) {
        this.productDesc = productDesc == null ? null : productDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.extra_info
     *
     * @return the value of product.extra_info
     *
     * @mbggenerated
     */
    public String getExtraInfo() {
        return extraInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.extra_info
     *
     * @param extraInfo the value for product.extra_info
     *
     * @mbggenerated
     */
    public void setExtraInfo(String extraInfo) {
        this.extraInfo = extraInfo == null ? null : extraInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.summary
     *
     * @return the value of product.summary
     *
     * @mbggenerated
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.summary
     *
     * @param summary the value for product.summary
     *
     * @mbggenerated
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.help
     *
     * @return the value of product.help
     *
     * @mbggenerated
     */
    public String getHelp() {
        return help;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.help
     *
     * @param help the value for product.help
     *
     * @mbggenerated
     */
    public void setHelp(String help) {
        this.help = help == null ? null : help.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.img1
     *
     * @return the value of product.img1
     *
     * @mbggenerated
     */
    public String getImg1() {
        return img1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.img1
     *
     * @param img1 the value for product.img1
     *
     * @mbggenerated
     */
    public void setImg1(String img1) {
        this.img1 = img1 == null ? null : img1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.img2
     *
     * @return the value of product.img2
     *
     * @mbggenerated
     */
    public String getImg2() {
        return img2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.img2
     *
     * @param img2 the value for product.img2
     *
     * @mbggenerated
     */
    public void setImg2(String img2) {
        this.img2 = img2 == null ? null : img2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.img3
     *
     * @return the value of product.img3
     *
     * @mbggenerated
     */
    public String getImg3() {
        return img3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.img3
     *
     * @param img3 the value for product.img3
     *
     * @mbggenerated
     */
    public void setImg3(String img3) {
        this.img3 = img3 == null ? null : img3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", cname=").append(cname);
        sb.append(", ename=").append(ename);
        sb.append(", type=").append(type);
        sb.append(", price=").append(price);
        sb.append(", starLevel=").append(starLevel);
        sb.append(", productDesc=").append(productDesc);
        sb.append(", extraInfo=").append(extraInfo);
        sb.append(", summary=").append(summary);
        sb.append(", help=").append(help);
        sb.append(", img1=").append(img1);
        sb.append(", img2=").append(img2);
        sb.append(", img3=").append(img3);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}